// front-end/movie-user-ui/app/(auth)/change-pass/ValidCodeForm.tsx
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';

import { Button } from '@/components/ui/button';
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import HeaderMobile from '@/components/ui/header-mobile';
import { InputOTP, InputOTPGroup, InputOTPSlot } from '@/components/ui/input-otp';
import { sendOtpCodeChangePassword, validCode } from '@/services/authServices';

const FormSchema = z.object({
    code: z.string().min(5, {
        message: 'Your code must be 6 number.',
    }),
});

type Props = {
    className?: string;
    email: string;
    onValidCode: () => void;
};

const ValidCodeForm = ({ className, email, onValidCode }: Props) => {
    const [loading, setLoading] = useState(false);
    const [reSendLoading, setReSendLoading] = useState(false);
    const form = useForm<z.infer<typeof FormSchema>>({
        resolver: zodResolver(FormSchema),
        defaultValues: {
            code: '',
        },
    });

    const onSubmit = (data: z.infer<typeof FormSchema>) => {
        const validCodeApi = async () => {
            if (loading) return;
            const res = await validCode({ email: email, code: data.code });
            if (res) {
                if (res.status === 200) {
                    onValidCode();
                } else {
                    form.setError('code', { message: res?.message });
                }
            } else {
                form.setError('code', { message: 'Some thing went wrong!' });
            }
            setLoading(false);
        };
        setLoading(true);
        validCodeApi();
    };

    const resendCode = (e: React.MouseEvent<HTMLButtonElement>) => {
        e.preventDefault();
        if (reSendLoading) return;
        setReSendLoading(true);
        const fetchApi = async () => {
            const res = await sendOtpCodeChangePassword(email);
            if (res && res.status !== 200) {
                form.setError('code', { message: 'Some thing went wrong!' });
            }
            setReSendLoading(false);
        };
        fetchApi();
    };
    return (
        <div className={`flex flex-col ${className ? className : ''}`}>
            <HeaderMobile title="Valid otp code" />
            <Form {...form}>
                <form
                    onSubmit={form.handleSubmit(onSubmit)}
                    className="mx-auto max-w-lg space-y-6 max-sm:w-full max-sm:px-10"
                >
                    <div>
                        <h2 className="mb-5 text-xl font-medium">
                            Please enter the one-time opt code sent to your email.
                        </h2>
                    </div>
                    <FormField
                        control={form.control}
                        name="code"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>One-Time Password</FormLabel>
                                <FormControl>
                                    <InputOTP maxLength={6} {...field}>
                                        <InputOTPGroup>
                                            <InputOTPSlot index={0} />
                                            <InputOTPSlot index={1} />
                                            <InputOTPSlot index={2} />
                                            <InputOTPSlot index={3} />
                                            <InputOTPSlot index={4} />
                                        </InputOTPGroup>
                                    </InputOTP>
                                </FormControl>
                                <FormDescription className="flex items-center">
                                    <p>Didn&apos;t receive the opt code?</p>
                                    <Button variant="link" onClick={resendCode}>
                                        Send again
                                    </Button>
                                </FormDescription>
                                <FormMessage />
                            </FormItem>
                        )}
                    />
                    <div className="mt-3 w-full">
                        <Button type="submit" loading={loading} disabled={loading} className="w-full">
                            Submit
                        </Button>
                    </div>
                </form>
            </Form>
        </div>
    );
};

export default ValidCodeForm;

// front-end/movie-admin-ui/src/app/features/auth/component/valid-code-form/valid-code-form.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { ButtonComponent } from '../../../../shared/components/ui/button/button.component';
import { ChangePassService } from '../../services/change-pass.service';
import { ToastService } from '../../../../core/services/toast.service';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ErrorDisplayComponent } from '../../../../shared/components/ui/error-display/error-display.component';
import { NgOtpInputModule } from 'ng-otp-input';
import { HeaderMobileComponent } from '../../../../shared/components/ui/header-mobile/header-mobile.component';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-valid-code-form',
  standalone: true,
  imports: [NgIf, ButtonComponent, ReactiveFormsModule, ErrorDisplayComponent, NgOtpInputModule, HeaderMobileComponent],
  templateUrl: './valid-code-form.component.html',
  styleUrl: './valid-code-form.component.scss',
})
export class ValidCodeFormComponent {
  @Input({ required: true }) email: string = '';

  @Output() onValidCode = new EventEmitter<void>();

  validCodeForm!: FormGroup;
  loading: boolean = false;
  reSendCodeLoading: boolean = false;
  isReSendCode: boolean = false;

  constructor(
    private changePasswordService: ChangePassService,
    private toastService: ToastService,
  ) {}

  ngOnInit(): void {
    this.validCodeForm = new FormGroup({
      code: new FormControl<string>('', [Validators.required, Validators.minLength(5), Validators.maxLength(5)]),
    });
  }

  getControl(name: string) {
    return this.validCodeForm.controls['code'] as FormControl<any>;
  }

  handleSubmit() {
    if (this.validCodeForm.status === 'INVALID') {
      return;
    }

    if (this.validCodeForm.value.code.length < 5) {
      return;
    }

    if (this.loading) return;
    this.loading = true;
    this.changePasswordService.validCode({ email: this.email, code: this.validCodeForm.value.code }).subscribe({
      next: (data) => {
        if (data.status === 200) {
          this.onValidCode.emit();
        }
        this.loading = false;
      },
      error: () => {
        this.toastService.showToast('danger', 'The code is incorrect. Please check again!', 4000);
        this.validCodeForm.controls['code'].reset();
        this.loading = false;
      },
    });
  }

  handleResendCode() {
    if (this.reSendCodeLoading) return;
    this.reSendCodeLoading = true;
    this.changePasswordService.sendOtpCodeChangePassword(this.email).subscribe({
      error: () => {
        this.toastService.showToast('danger', 'Some thing went wrong! Try again later!');
      },
      complete: () => {
        this.isReSendCode = true;
        this.reSendCodeLoading = false;
      },
    });
  }
}

<div class="flex flex-col">
  <app-header-mobile title="Valid code" />
  <form
    class="mx-auto max-w-lg space-y-6 max-sm:w-full max-sm:px-10"
    [formGroup]="validCodeForm"
    (ngSubmit)="handleSubmit()"
  >
    <div>
      <h5 class="mb-5 text-xl font-medium">Please enter the one-time opt code sent to your email.</h5>
    </div>

    <div>
      <div class="mb-2">
        <label for="code" class="mb-2">Otp code</label>

        <ng-otp-input
          id="code"
          [formCtrl]="getControl('code')"
          [config]="{ length: 5, allowNumbersOnly: true }"
        ></ng-otp-input>
      </div>

      <app-error-display [control]="validCodeForm.controls['code']" [isFormSubmitted]="false" />
      <div class="flex items-center text-sm text-gray-500">
        <p>Didn&apos;t receive the opt code?</p>
        <app-button
          variant="link"
          (click)="handleResendCode()"
          [loading]="reSendCodeLoading"
          [disabled]="reSendCodeLoading"
        >
          Send again
        </app-button>
      </div>
      <div *ngIf="isReSendCode && !reSendCodeLoading" class="flex items-center text-sm text-gray-500">
        Check your email again!
      </div>
    </div>

    <div class="w-ful">
      <app-button type="submit" class="w-full" [loading]="loading" [disabled]="loading"> Submit </app-button>
    </div>
  </form>
</div>
