// front-end/movie-admin-ui/src/app/shared/components/ui/header-mobile/header-mobile.component.ts
import { Location } from '@angular/common';
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-header-mobile',
  standalone: true,
  imports: [],
  templateUrl: './header-mobile.component.html',
  styleUrl: './header-mobile.component.scss',
})
export class HeaderMobileComponent {
  @Input() title: string = 'Title';

  constructor(private location: Location) {}

  back() {
    this.location.back();
  }
}

<div class="mb-3 flex items-center gap-x-3">
  <button class="cursor-pointer rounded-lg bg-accent p-1.5 active:scale-90" (click)="back()">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="size-5"
    >
      <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
    </svg>
  </button>
  <div class="font-medium">{{ title }}</div>
</div>

// front-end/movie-user-ui/components/ui/header-mobile.tsx
'use client';
import { ChevronLeft } from 'lucide-react';
import { useRouter } from 'next/navigation';
import React from 'react';

type Props = {
    title: string;
};

const HeaderMobile = ({ title }: Props) => {
    const router = useRouter();
    return (
        <div className="mb-3 flex items-center gap-x-3">
            <button className="cursor-pointer rounded-lg bg-accent p-1.5 active:scale-90" onClick={() => router.back()}>
                <ChevronLeft className="size-5" />
            </button>
            <p className="font-medium">{title}</p>
        </div>
    );
};

export default HeaderMobile;
