// front-end/movie-admin-ui/src/app/shared/components/ui/marquee-text/marquee-text.component.ts
import { NgClass, NgStyle } from '@angular/common';
import { AfterViewInit, Component, ElementRef, Input, OnInit, ViewChild } from '@angular/core';

@Component({
    selector: 'app-marquee-text',
    standalone: true,
    imports: [NgClass, NgStyle],
    templateUrl: './marquee-text.component.html',
    styleUrl: './marquee-text.component.css',
})
export class MarqueeTextComponent implements AfterViewInit {
    @Input({ required: true }) text: string = '';
    @Input() duration: number = 0;
    @Input() class: string = '';
    @ViewChild('containerRef') containerRef!: ElementRef<HTMLDivElement>;
    @ViewChild('textRef') textRef!: ElementRef<HTMLDivElement>;

    isOverFlowing: boolean = false;
    scrollPosition: number = 0;

    ngAfterViewInit(): void {
        if (this.containerRef && this.textRef) {
            const textWidth = this.textRef.nativeElement.scrollWidth;
            const containerWidth = this.containerRef.nativeElement.offsetWidth;
            this.isOverFlowing = textWidth > containerWidth;
        }
    }

    handleMouseEnter() {
        if (this.isOverFlowing) {
            const textWidth = this.textRef.nativeElement?.scrollWidth ?? 0;
            const containerWidth = this.containerRef.nativeElement?.offsetWidth ?? 0;
            this.scrollPosition = textWidth - containerWidth;
            setTimeout(
                () => {
                    this.scrollPosition = 0;
                },
                this.duration ? this.duration * 1000 + 2000 : 2000,
            );
        }
    }
}

<div #containerRef class="w-full overflow-hidden whitespace-nowrap" (mouseenter)="handleMouseEnter()">
    <div
        #textRef
        class="inline-block transition-transform ease-linear"
        [ngClass]="class"
        [style.transform]="isOverFlowing ? 'translateX(-' + scrollPosition + 'px)' : 'translateX(0)'"
        [ngStyle]="{
            animationDuration: duration ? duration + 's' : '1s',
            transitionDuration: duration ? duration + 's' : '1s',
        }"
    >
        {{ text }}
    </div>
</div>

// front-end/movie-user-ui/components/ui/marquee-text.tsx
'use client';
import React, { useRef, useState, useEffect } from 'react';

interface MarqueeTextProps {
    text: string;
    duration?: number;
    className?: string;
}

const MarqueeText: React.FC<MarqueeTextProps> = ({ text, duration, className = '' }) => {
    const textRef = useRef<HTMLDivElement>(null);
    const containerRef = useRef<HTMLDivElement>(null);
    const [isOverflowing, setIsOverflowing] = useState(false);
    const [scrollPosition, setScrollPosition] = useState(0);

    useEffect(() => {
        if (textRef.current && containerRef.current) {
            const textWidth = textRef.current.scrollWidth;
            const containerWidth = containerRef.current.offsetWidth;
            setIsOverflowing(textWidth > containerWidth);
        }
    }, [text]);

    const handleMouseEnter = () => {
        if (isOverflowing) {
            const textWidth = textRef.current?.scrollWidth ?? 0;
            const containerWidth = containerRef.current?.offsetWidth ?? 0;
            setScrollPosition(textWidth - containerWidth);
            setTimeout(
                () => {
                    setScrollPosition(0);
                },
                duration ? duration * 1000 + 2000 : 2000,
            );
        }
    };

    return (
        <div ref={containerRef} className="overflow-hidden whitespace-nowrap" onMouseEnter={handleMouseEnter}>
            <div
                ref={textRef}
                className={`inline-block transition-transform ease-linear ${className}`}
                style={{
                    transform: isOverflowing ? `translateX(-${scrollPosition}px)` : 'translateX(0)',
                    animationDuration: duration ? duration + 's' : '1s',
                    transitionDuration: duration ? duration + 's' : '1s',
                }}
            >
                {text}
            </div>
        </div>
    );
};

export default MarqueeText;
