// front-end/movie-admin-ui/src/app/features/auth/component/change-password-form/change-password-form.component.ts
import { NgIf } from '@angular/common';
import { Component, Input } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { heroEye, heroEyeSlash } from '@ng-icons/heroicons/outline';
import { ToastService } from '../../../../core/services/toast.service';
import { ButtonComponent } from '../../../../shared/components/ui/button/button.component';
import { HeaderMobileComponent } from '../../../../shared/components/ui/header-mobile/header-mobile.component';
import { ChangePassService } from '../../services/change-pass.service';

@Component({
  selector: 'app-change-password-form',
  standalone: true,
  imports: [ReactiveFormsModule, ButtonComponent, NgIf, NgIconComponent, HeaderMobileComponent],
  templateUrl: './change-password-form.component.html',
  styleUrl: './change-password-form.component.scss',
  providers: [
    provideIcons({
      heroEye,
      heroEyeSlash,
    }),
  ],
})
export class ChangePasswordFormComponent {
  @Input({ required: true }) email: string = '';

  showPassword: boolean = false;
  changePasswordForm!: FormGroup;
  loading: boolean = false;

  constructor(
    private changePasswordService: ChangePassService,
    private toastService: ToastService,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.changePasswordForm = new FormGroup(
      {
        newPassword: new FormControl<string>('', [
          Validators.required,
          Validators.pattern(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).*$/),
        ]),
        confirmPassword: new FormControl<string>('', [
          Validators.required,
          Validators.pattern(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).*$/),
        ]),
      },
      this.changePasswordService.passwordMatch('newPassword', 'confirmPassword'),
    );
  }

  getControl(name: string) {
    return this.changePasswordForm.controls['code'] as FormControl<any>;
  }

  handleSubmit() {
    if (this.changePasswordForm.status === 'INVALID') {
      return;
    }
    if (this.loading) return;
    this.loading = true;
    this.changePasswordService
      .changePassword({ email: this.email, newPassword: this.changePasswordForm.value.newPassword })
      .subscribe({
        next: (data) => {
          if (data.status === 200) {
            this.router.navigate(['/']);
          }
          this.loading = false;
        },
        error: () => {
          this.toastService.showToast('danger', 'Some thing went wrong! Try again later!');
          this.loading = false;
        },
      });
  }

  handleToggleShowPassword() {
    this.showPassword = !this.showPassword;
  }
}

<div class="flex w-full flex-col">
  <app-header-mobile title="Reset password" />
  <form
    class="mx-auto w-96 space-y-6 max-sm:w-full max-sm:px-10"
    [formGroup]="changePasswordForm"
    (ngSubmit)="handleSubmit()"
  >
    <div>
      <h5 class="mb-5 text-xl font-medium">Update your password!</h5>
    </div>

    <div>
      <div class="mb-2">
        <label for="newPassword">New password</label>

        <input
          id="newPassword"
          [type]="showPassword ? 'text' : 'password'"
          formControlName="newPassword"
          placeholder="******"
          class="mt-2 block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-primary focus:ring-primary dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-primary dark:focus:ring-primary"
        />
      </div>

      <div
        *ngIf="
          changePasswordForm.controls['newPassword'].invalid &&
          (changePasswordForm.controls['newPassword'].dirty || changePasswordForm.controls['newPassword'].touched)
        "
        class="mt-2 w-full text-left"
      >
        <div
          class="text-sm italic text-red-500"
          *ngIf="changePasswordForm.controls['newPassword'].hasError('required')"
        >
          This filed is required.
        </div>
        <div class="text-sm italic text-red-500" *ngIf="changePasswordForm.controls['newPassword'].hasError('pattern')">
          Password must contain at least one uppercase letter, one lowercase letter, and one digit.
        </div>
      </div>

      <p class="text-sm text-gray-500">Please enter your new password.</p>
    </div>

    <div>
      <div class="mb-2">
        <label for="confirmPassword">Confirm password</label>

        <input
          id="confirmPassword"
          [type]="showPassword ? 'text' : 'password'"
          formControlName="confirmPassword"
          placeholder="******"
          class="mt-2 block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-primary focus:ring-primary dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-primary dark:focus:ring-primary"
        />

        <div
          *ngIf="
            changePasswordForm.controls['confirmPassword'].invalid &&
            (changePasswordForm.controls['confirmPassword'].dirty ||
              changePasswordForm.controls['confirmPassword'].touched)
          "
          class="mt-2 w-full text-left"
        >
          <div
            class="text-sm italic text-red-500"
            *ngIf="changePasswordForm.controls['confirmPassword'].hasError('required')"
          >
            This filed is required.
          </div>
          <div
            class="text-sm italic text-red-500"
            *ngIf="changePasswordForm.controls['confirmPassword'].hasError('pattern')"
          >
            Password must contain at least one uppercase letter, one lowercase letter, and one digit.
          </div>
          <div
            class="text-sm italic text-red-500"
            *ngIf="changePasswordForm.controls['confirmPassword'].hasError('passwordMismatch')"
          >
            Confirm password does not match.
          </div>
        </div>
        <p
          class="mt-2 flex w-fit cursor-pointer items-center gap-x-2 text-sm text-gray-500"
          (click)="handleToggleShowPassword()"
        >
          <span>Show password</span>
          <ng-icon *ngIf="showPassword" name="heroEye"></ng-icon>
          <ng-icon *ngIf="!showPassword" name="heroEyeSlash"></ng-icon>
        </p>
      </div>
    </div>

    <div class="w-ful mt-3">
      <app-button type="submit" class="w-full"> Change password </app-button>
    </div>
  </form>
</div>

// front-end/movie-user-ui/app/(auth)/change-pass/ChangePasswordForm.tsx
import { Button } from '@/components/ui/button';
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import HeaderMobile from '@/components/ui/header-mobile';
import { Input } from '@/components/ui/input';
import { useToast } from '@/components/ui/use-toast';
import { changePassword } from '@/services/authServices';
import { zodResolver } from '@hookform/resolvers/zod';
import { Eye, EyeOff } from 'lucide-react';
import { useRouter } from 'next/navigation';
import React, { Fragment, useState } from 'react';
import { useForm } from 'react-hook-form';

import { z } from 'zod';

const FormSchema = z
    .object({
        newPassword: z.string().regex(new RegExp(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).*$/), {
            message: 'Password must contain at least one uppercase letter, one lowercase letter, and one digit.',
        }),
        confirmPassword: z.string().regex(new RegExp(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).*$/), {
            message: 'Password must contain at least one uppercase letter, one lowercase letter, and one digit.',
        }),
    })
    .superRefine(({ newPassword, confirmPassword }, ctx) => {
        if (confirmPassword !== newPassword) {
            ctx.addIssue({
                code: 'custom',
                message: 'The confirm did not match',
                path: ['confirmPassword'],
            });
        }
    });

type Props = {
    className?: string;
    email: string;
};

const ChangePasswordForm = ({ email, className }: Props) => {
    const [loading, setLoading] = useState(false);
    const [showPassword, setShowPassword] = useState(false);
    const form = useForm<z.infer<typeof FormSchema>>({
        resolver: zodResolver(FormSchema),
        defaultValues: {
            newPassword: '',
            confirmPassword: '',
        },
    });
    const { toast } = useToast();
    const router = useRouter();

    const onSubmit = (data: z.infer<typeof FormSchema>) => {
        const changePasswordApi = async () => {
            if (loading) return;
            const res = await changePassword({ email, newPassword: data.newPassword });
            if (res) {
                if (res.status === 200) {
                    toast({
                        title: 'Congratulations',
                        description: res.message,
                    });
                    router.push('/sign-in');
                } else {
                    form.setError('newPassword', { message: res?.message });
                }
            } else {
                form.setError('newPassword', { message: 'Some thing went wrong!' });
            }
            setLoading(false);
        };

        setLoading(true);
        changePasswordApi();
    };

    const handleShowPassword = () => {
        setShowPassword((prev) => !prev);
    };
    return (
        <div className={`flex flex-col ${className ? className : ''}`}>
            <HeaderMobile title="Update your password" />
            <Form {...form}>
                <form
                    onSubmit={form.handleSubmit(onSubmit)}
                    className="mx-auto max-w-lg space-y-6 max-sm:w-full max-sm:px-10"
                >
                    <div>
                        <h2 className="mb-5 text-xl font-medium">Enter your new password to complete!</h2>
                    </div>
                    <FormField
                        control={form.control}
                        name="newPassword"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>New password</FormLabel>
                                <FormControl>
                                    <Input type={showPassword ? 'text' : 'password'} placeholder="*****" {...field} />
                                </FormControl>
                                <FormMessage />
                                <FormDescription>Please enter your new password.</FormDescription>
                            </FormItem>
                        )}
                    />
                    <FormField
                        control={form.control}
                        name="confirmPassword"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>Confirm password</FormLabel>
                                <FormControl>
                                    <Input type={showPassword ? 'text' : 'password'} placeholder="*****" {...field} />
                                </FormControl>
                                <FormMessage />
                                <FormDescription
                                    className="flex cursor-default items-center gap-x-2"
                                    onClick={handleShowPassword}
                                >
                                    Show password{' '}
                                    {showPassword ? (
                                        <Eye className="size-4 cursor-pointer text-gray-700" />
                                    ) : (
                                        <EyeOff className="size-4 cursor-pointer text-gray-700" />
                                    )}
                                </FormDescription>
                            </FormItem>
                        )}
                    />
                    <div className="mt-3 w-full">
                        <Button type="submit" loading={loading} disabled={loading} className="w-full">
                            Submit
                        </Button>
                    </div>
                </form>
            </Form>
        </div>
    );
};

export default ChangePasswordForm;
