// front-end/movie-admin-ui/src/app/features/auth/component/change-pass/change-pass.component.ts
import { NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { SendOtpFormComponent } from '../send-otp-form/send-otp-form.component';
import { ValidCodeFormComponent } from '../valid-code-form/valid-code-form.component';
import { ChangePasswordFormComponent } from '../change-password-form/change-password-form.component';

@Component({
  selector: 'app-change-pass',
  standalone: true,
  imports: [NgIf, SendOtpFormComponent, ValidCodeFormComponent, ChangePasswordFormComponent],
  templateUrl: './change-pass.component.html',
  styleUrl: './change-pass.component.scss',
})
export class ChangePassComponent {
  step: 'sendOtpCode' | 'validCode' | 'changePassword' = 'sendOtpCode';
  currentEmail: string = '';

  handleSendOtpCodeChangePassword = (email: string) => {
    this.currentEmail = email;
    this.handleChangeForm();
  };

  handleChangeForm = () => {
    switch (this.step) {
      case 'sendOtpCode':
        this.step = 'validCode';
        break;
      case 'validCode':
        this.step = 'changePassword';
        break;
      default:
        this.step = 'sendOtpCode';
    }
  };
}

<div class="flex h-full w-full flex-col items-center justify-center">
  <app-send-otp-form
    *ngIf="step === 'sendOtpCode'"
    (onSendOtpCodeChangePassword)="handleSendOtpCodeChangePassword($event)"
  />
  <app-valid-code-form *ngIf="step === 'validCode'" [email]="currentEmail" (onValidCode)="handleChangeForm()" />
  <app-change-password-form *ngIf="step === 'changePassword'" [email]="currentEmail" />
</div>

// front-end/movie-user-ui/app/(auth)/change-pass/page.tsx
'use client';
import React, { Fragment, useState } from 'react';
import SendOtpCodeForm from './SendOtpCodeForm';
import ValidCodeForm from './ValidCodeForm';
import ChangePasswordForm from './ChangePasswordForm';
import { cn } from '@/lib/utils';

type Props = {};

const ChangePassPage = (props: Props) => {
    const [step, setStep] = useState<'sendOtpCode' | 'validCode' | 'changePassword'>('sendOtpCode');
    const [currentEmail, setCurrentEmail] = useState<string>('');
    const [shouldRender, setShouldRender] = useState(false);

    const handleSendOtpCodeChangePassword = (email: string) => {
        setCurrentEmail(email);
        setStep('validCode');
    };

    const handleValidCode = () => {
        setStep('changePassword');
        setTimeout(() => {
            setShouldRender(false);
        }, 500);

        setTimeout(() => {
            setShouldRender(true);
        }, 800);
    };

    const handleChangeForm = () => {
        switch (step) {
            case 'sendOtpCode':
                setStep('validCode');
                break;
            case 'validCode':
                setStep('changePassword');
                break;
            default:
                setStep('sendOtpCode');
        }
    };
    return (
        <div className="flex flex-col">
            {step === 'sendOtpCode' && (
                <SendOtpCodeForm onSendOtpCodeChangePassword={handleSendOtpCodeChangePassword} />
            )}

            {step === 'validCode' && <ValidCodeForm email={currentEmail} onValidCode={handleValidCode} />}
            {step === 'changePassword' && <ChangePasswordForm email={currentEmail} />}
        </div>
    );
};

export default ChangePassPage;
