// front-end/movie-user-ui/components/shared/Search.tsx
'use client';

import React, { useEffect, useRef, useState } from 'react';
import { Input } from '../ui/input';
import { motion } from 'framer-motion';
import { useRouter } from 'next/navigation';
import { useDebounce } from '@/hooks';
import Image from 'next/image';
import { DropdownMenu, DropdownMenuItem } from '../ui/dropdown-menu-custom';
import { LoaderCircle } from 'lucide-react';
import { cn } from '@/lib/utils';

type Props = {
    className?: string;
};

function Search({ className }: Props) {
    const router = useRouter();
    const [searchValue, setSearchValue] = useState('');
    const [searchResult, setSearchResult] = useState<string[]>([]);
    const [showResult, setShowResult] = useState(true);
    const [loading, setLoading] = useState(false);

    const debounced = useDebounce<string>(searchValue, 500);

    const inputRef = useRef<HTMLInputElement>(null);

    const handleClear = () => {
        setSearchValue('');
        setSearchResult([]);
        if (inputRef.current !== null) {
            inputRef.current.focus();
        }
    };

    const handleHideResult = () => {
        setShowResult(false);
    };

    useEffect(() => {
        if (!debounced.trim()) {
            setSearchResult([]);
            return;
        }

        const fetchApi = async () => {
            setLoading(true);

            // const response = await fetch(`https://api.themoviedb.org/3/search/movie?query=${debounced}`, {
            //     headers: {
            //         Authorization:
            //             'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMTQxODgzNDUzN2I0MThjYWE2MGYxYTM1Njk5YWFlNSIsIm5iZiI6MTcyMTMxODM3NS4wNzQ5MzQsInN1YiI6IjY2OTkzYWVhZGExMjIxZjdmM2NlOWI5MSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.G-fUWJhJCjqA0MbSnzUZ0j1cyUrNOSdBQT1Fih8CHik',
            //     },
            // });
            // const data = await response.json();
            // TODO: delete this block code
            const res = await new Promise<void>((resolve, reject) => {
                setTimeout(() => {
                    resolve();
                }, 1000);
            });
            const fakeData = ['result 1', 'result 2'];
            fakeData.push(debounced);
            setSearchResult(fakeData);

            setLoading(false);
        };

        if (searchResult.some((r) => r === debounced)) {
            return;
        }

        fetchApi();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [debounced]);

    const handleSearchInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const searchValue = e.target.value;
        if (!searchValue.startsWith(' ')) {
            setSearchValue(searchValue);
        }
    };

    const handleOnKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        const indexSearchKeyword = searchResult.indexOf(searchValue);
        if (e.key === 'ArrowDown') {
            if (indexSearchKeyword === searchResult.length - 1) {
                setSearchValue(searchResult[0]);
            } else if (indexSearchKeyword + 1 < searchResult.length) {
                setSearchValue(searchResult[indexSearchKeyword + 1]);
            }
        } else if (e.key === 'ArrowUp') {
            if (indexSearchKeyword === 0) {
                setSearchValue(searchResult[searchResult.length - 1]);
            } else {
                setSearchValue(searchResult[indexSearchKeyword - 1]);
            }
        } else if (e.key === 'Enter') {
            alert('submit');
            e.preventDefault();
        }
    };

    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        alert('submit');
    };

    const handleKeyPress = (event: React.KeyboardEvent) => {
        if (event.key === 'Enter') {
            router.push('/search');
        }
    };

    return (
        <form
            className={cn(
                'relative w-96 rounded-xl border-2 border-gray-300 px-3 focus-within:border-primary max-sm:w-64',
                { [className as string]: className },
            )}
        >
            <div className="relative flex items-center">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className="size-6 dark:fill-white"
                >
                    <motion.path
                        variants={{
                            hidden: {
                                pathLength: 0,
                                fill: 'rgba(255, 255, 255, 0)',
                            },
                            visible: {
                                pathLength: 1,
                                fill: 'rgba(255, 255, 255, 1)',
                            },
                        }}
                        initial="hidden"
                        animate="visible"
                        transition={{ duration: 0.5 }}
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"
                    />
                </svg>
                <Input
                    ref={inputRef}
                    className="no-focus mr-4 border-none bg-transparent outline-none"
                    value={searchValue}
                    placeholder="Search..."
                    onFocus={() => setShowResult(true)}
                    onChange={handleSearchInputChange}
                    onKeyDown={handleOnKeyDown}
                />
                {showResult && searchResult && searchResult.length > 0 && (
                    <DropdownMenu
                        className="absolute -left-4 top-12 w-96 max-sm:w-64"
                        title="Movie"
                        onOutSideClick={handleHideResult}
                    >
                        {searchResult.slice(0, searchResult.length - 1).map((result) => (
                            <DropdownMenuItem key={result} isFocused={searchValue === result}>
                                {result}
                            </DropdownMenuItem>
                        ))}
                    </DropdownMenu>
                )}
                {loading && <LoaderCircle className="size-6 animate-spin dark:text-white" />}
                {searchValue && !loading && (
                    <button className="absolute right-0" onClick={handleClear}>
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            strokeWidth={1.5}
                            stroke="currentColor"
                            className="size-6"
                        >
                            <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
                            />
                        </svg>
                    </button>
                )}
            </div>
        </form>
    );
}

export default Search;

// front-end/movie-admin-ui/src/app/shared/components/ui/search/search.component.ts
import { NgClass, NgFor, NgIf } from '@angular/common';
import { Component, ElementRef, HostListener, Input, ViewChild } from '@angular/core';
import { BehaviorSubject, debounce, debounceTime } from 'rxjs';
import { OutsideClickDirective } from '../../../directives/outside-click.directive';
import { SearchMenuItemComponent } from '../search-menu-item/search-menu-item.component';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { heroMagnifyingGlass } from '@ng-icons/heroicons/outline';
import { LabelAndValue } from '../../../models/labelAndValue';
import { Router } from '@angular/router';

@Component({
  selector: 'app-search',
  standalone: true,
  imports: [NgIf, NgFor, NgClass, OutsideClickDirective, SearchMenuItemComponent, NgIconComponent],
  templateUrl: './search.component.html',
  styleUrl: './search.component.scss',
  viewProviders: [
    provideIcons({
      heroMagnifyingGlass,
    }),
  ],
})
export class SearchComponent {
  @Input() class: string = '';
  private listResults: Array<LabelAndValue> = [
    { label: 'dashboard', value: '/' },
    { label: 'schedule', value: '/schedule' },
    { label: 'do schedule', value: '/schedule/manage/do-schedule' },
    { label: 'add new showing', value: '/showing/manage/create' },
    { label: 'users', value: '/users' },
    { label: 'movies', value: '/movies' },
    { label: 'add new movie', value: '/movies/adding' },
    { label: 'halls', value: '/hall' },
    { label: 'genres', value: '/genres' },
    { label: 'orders', value: '/orders' },
    { label: 'profile', value: '/profile' },
  ];
  searchResults: Array<LabelAndValue> = [];
  searchValue = new BehaviorSubject<string>('');
  searchValueDisplay: string = '';
  showResult: boolean = false;
  loading: boolean = false;

  constructor(private router: Router) {
    this.searchValue.pipe(debounceTime(500)).subscribe((searchTerm: string) => {
      if (!searchTerm.trim()) {
        this.searchResults = [];
        return;
      }

      const filter = async () => {
        if (this.loading) return;
        this.loading = true;

        const filterKeyword = new Promise<Array<LabelAndValue>>((resolve, reject) => {
          setTimeout(() => {
            let results = this.listResults.filter((r) =>
              r.label.toLocaleLowerCase().includes(searchTerm.toLocaleLowerCase()),
            );
            results = [{ label: searchTerm, value: '' }, ...results];
            resolve(results);
          }, 400);
        });

        this.searchResults = await filterKeyword;
        this.loading = false;
      };

      filter();
    });
  }

  @ViewChild('searchInput') searchInput!: ElementRef;

  handleClear() {
    this.searchValueDisplay = '';
    this.searchResults = [];
    if (this.searchInput) {
      this.searchInput.nativeElement.focus();
    }
  }

  handleHideResults() {
    this.showResult = false;
  }

  @HostListener('window:keydown', ['$event'])
  handleKeyDown(event: KeyboardEvent) {
    if (event.key === '/') {
      event.preventDefault();
      this.searchInput.nativeElement.focus();
      this.showResult = true;
    }
  }

  handleSearchInputChange(e: Event) {
    const searchValue = (e.target as HTMLInputElement).value;

    if (!searchValue.startsWith(' ')) {
      this.searchValueDisplay = searchValue;
      this.searchValue.next(searchValue);
    }
  }

  handleOnKeyDown(e: KeyboardEvent) {
    const indexSearchKeyword = this.searchResults.map((rs) => rs.label).indexOf(this.searchValueDisplay);
    const searchResultsLength = this.searchResults.length;

    if (e.key === 'ArrowDown') {
      if (indexSearchKeyword === searchResultsLength - 1) {
        this.searchValueDisplay = this.searchResults[0].label;
      } else if (indexSearchKeyword + 1 < searchResultsLength) {
        this.searchValueDisplay = this.searchResults[indexSearchKeyword + 1].label;
      }
    } else if (e.key === 'ArrowUp') {
      if (indexSearchKeyword === 0) {
        this.searchValueDisplay = this.searchResults[searchResultsLength - 1].label;
      } else {
        this.searchValueDisplay = this.searchResults[indexSearchKeyword - 1].label;
      }
    } else if (e.key === 'Enter') {
      if (this.searchResults[indexSearchKeyword].value !== '') {
        this.router.navigate([this.searchResults[indexSearchKeyword].value]);
      }
      this.showResult = false;
      e.preventDefault();
    }
  }

  handleChooseItem(item: LabelAndValue) {
    this.searchValueDisplay = item.label;
    this.showResult = false;
    if (item.value !== '') {
      this.router.navigate([item.value]);
    }
  }
}

<div
  class="relative w-96 rounded-xl border-2 border-gray-300 px-3 focus-within:border-primary max-lg:w-64"
  [ngClass]="class"
>
  <div class="relative flex items-center">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      strokeWidth="{1.5}"
      stroke="currentColor"
      class="size-6 dark:fill-white"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"
      />
    </svg>
    <input
      #searchInput
      type="text"
      class="block w-full rounded-lg bg-gray-50 p-2.5 text-sm text-gray-900 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400"
      placeholder="Search..."
      [value]="searchValueDisplay"
      (focus)="showResult = true"
      (input)="handleSearchInputChange($event)"
      (keydown)="handleOnKeyDown($event)"
    />

    <div
      *ngIf="showResult && searchResults && searchResults.length > 0"
      role="menu"
      tabIndex="{-1}"
      data-orientation="vertical"
      class="absolute -left-4 top-12 z-50 w-96 bg-white py-2 max-lg:w-64"
      [appOutsideClick]="showResult"
      (outSideClick)="showResult = false"
    >
      <ng-container *ngFor="let result of searchResults">
        <app-search-menu-item [isFocused]="searchValueDisplay === result.label" (click)="handleChooseItem(result)">
          <div class="flex items-center gap-x-3">
            <ng-icon name="heroMagnifyingGlass" size="24" class="text-gray-500"></ng-icon>
            {{ result.label }}
          </div>
        </app-search-menu-item>
      </ng-container>
    </div>

    <div *ngIf="loading" role="status">
      <svg
        aria-hidden="true"
        class="size-6 animate-spin fill-orange-600 text-gray-200 dark:text-gray-600"
        viewBox="0 0 100 101"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
          fill="currentColor"
        />
        <path
          d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
          fill="currentFill"
        />
      </svg>
      <span class="sr-only">Loading...</span>
    </div>

    <button *ngIf="searchValue.getValue() !== '' && !loading" class="absolute right-0" (click)="handleClear()">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth="{1.5}"
        stroke="currentColor"
        class="size-6"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
        />
      </svg>
    </button>
  </div>
</div>
